AllCops:
  SuggestExtensions: false
  NewCops: enable
  TargetRubyVersion: 3.2
  Exclude:
    - src/**/*
    - pkg/**/*
    - vendor/**/*
    - test/**/*

Naming/FileName:
  Exclude:
    - lib/libv8-node.rb

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Layout/LineLength:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/SuperWithArgsParentheses:
  Enabled: false

Gemspec/DevelopmentDependencies:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false
