#!/bin/sh

set -e
set -u

version="${1}"

NJOBS="${NJOBS:-$(getconf _NPROCESSORS_ONLN 2>/dev/null || true)}"
NJOBS="${NJOBS:-1}"

cd "src/node-${version}"

python3 configure --openssl-no-asm --without-npm --shared --with-intl=small-icu --experimental-enable-pointer-compression
make -j"${NJOBS}"

# taken from
# ./configure
# make
#   make -C out BUILDTYPE=Release V=1

#python configure.py --openssl-no-asm --without-npm
#make BUILDTYPE=Release out/Makefile
#make -C out BUILDTYPE=Release V=1 v8
#make -C out BUILDTYPE=Release V=1 v8_libbase
#make -C out BUILDTYPE=Release V=1 v8_libplatform
#make -C out BUILDTYPE=Release V=1 v8_libsampler

