#!/bin/sh

set -e
set -u

version="${1}"

cd "src/node-${version}"

BASEDIR="${PWD}"
BUILDTYPE="${BUILDTYPE:-Release}"
LIBV8_MONOLITH="libv8_monolith.a"

cd "out/${BUILDTYPE}/obj.target"

platform=$(uname)

rm -f "${LIBV8_MONOLITH}"
case "${platform}" in
    "SunOS")
        /usr/xpg4/bin/find . -path "./v8*/**/*.o" -or -path "./icu*/**/*.o" | sort | uniq | \
            xargs ar cqS "${LIBV8_MONOLITH}"
        ranlib "${LIBV8_MONOLITH}"
        ;;
    "Darwin")
        /usr/bin/find . -path "./v8*/**/*.o" -or -path "./icu*/**/*.o" | sort | uniq | while read -r obj; do
            /usr/bin/ar -cqS "${LIBV8_MONOLITH}" "${obj}"
        done
        /usr/bin/ranlib "${LIBV8_MONOLITH}"
        ;;
    "Linux")
        find . -path './tools/v8/gypfiles/*.a' | while read -r lib; do
          ar -t "${lib}" | xargs ar -cqS "${LIBV8_MONOLITH}"
        done
        find . -path './tools/icu/*.a' | while read -r lib; do
          ar -t "${lib}" | xargs ar -cqS "${LIBV8_MONOLITH}"
        done
        ranlib "${LIBV8_MONOLITH}"
        ;;
    *)
      echo "Unsupported platform: ${platform}"
      exit 1
      ;;
esac

mv -f "${LIBV8_MONOLITH}" "${BASEDIR}/out/${BUILDTYPE}/${LIBV8_MONOLITH}"
