#!/bin/sh

set -e
set -u

version="${1}"

platform=$(uname)

case "${platform}" in
    SunOS)
        TAR="${TAR:-gtar}"
        ;;
    *)
        TAR="${TAR:-tar}"
        ;;
esac

"${TAR}" -C src -xz -f "src/node-${version}.tar.gz"
