#!/bin/sh

set -e
set -u

version="${1}"

platform=$(uname)

case "${platform}" in
    SunOS)
        CURLOPTS="${CURLOPTS:--k}"
        ;;
    *)
        CURLOPTS="${CURLOPTS:-}"
        ;;
esac

mkdir -p src

curl ${CURLOPTS} -L -o "src/node-${version}.tar.gz" "https://github.com/nodejs/node/archive/v${version}.tar.gz"
